# Generated by Django 3.0.6 on 2021-08-31 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=250)),
                ('jounalis', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('kontni', models.TextField()),
                ('dat_pibliye', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
