# Generated by Django 3.0.6 on 2021-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atik',
            name='kontni',
            field=models.TextField(max_length=5000),
        ),
    ]
