# Generated by Django 3.0.6 on 2021-08-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210831_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atik',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
